spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true 
      use_sql_comments: true
  social:
    facebook:
      app-id: 2246330218761993
      app-secret: d934e29a113c5a5044cae12737fe3467
      scope: public_profile, email, user_birthday
      redirect-url: http://localhost:8082/facebookToken?temporaryCode=
  mustache:
    suffix: .html
server:
  port: 8082
---
spring:
  profiles: local
  datasource:
    platform: mariadb  
    driver-class-name: org.mariadb.jdbc.Driver  
    url: jdbc:mariadb://192.168.99.100:3306/with-kid
    username: root  
    password: 1234  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
spring:
  profiles: production
  datasource:
    platform: mariadb  
    driver-class-name: org.mariadb.jdbc.Driver  
    url: jdbc:mariadb://withkid_rdb:3306/with-kid
    username: root  
    password: 1234  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
spring:
  profiles: test
  jpa:
    hibernate: 
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true 
      use_sql_comments: true
  output: 
     ansi: 
      enabled: always
  social:
    facebook:
      app-id: 2246330218761993
      app-secret: d934e29a113c5a5044cae12737fe3467
